# Generated by Django 6.0.1 on 2026-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="details",
            field=models.TextField(null=True),
        ),
    ]
