# Generated by Django 5.0.14 on 2026-02-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0003_seed_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="short_code",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
